name: Build

on:
  push:
    branches: [ madness-makeover ]
  pull_request:
    branches: [ madness-makeover ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: latest
          
      - name: Install Haxe Dependencies
        run: |
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install actuate
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install hxcpp
          haxelib install hxWebP
        
      - name: Build Windows
        run: haxelib run lime build windows -debug
        
      - name: Build Linux
        run: haxelib run lime build linux -debug
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            export/html5/bin
            export/windows/bin
            export/linux/bin